[tool.poetry]
name = "cwork"
version = "0.1.0"
description = ""
authors = ["BulatMr <morzag1@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
